version: '3.8'
services:
  falcon-app:
    image: ernestklu/falcon-look-app:latest
    ports:
      - 3080:8000
  postgresdb:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd