#!/usr/bin/env groovy
def gv

pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage('init') {
            steps {
                script {
                    gv = load "./jenkins-params-build/script.groovy"
                }
                
            }
        }
        stage('test') {
            steps {
                script {
                    env.PICK = input message: "Select whether to test or not", ok: "Done",
                    parameters: [choice(name: "CHOOSE", choices: ['Yes', 'No'], description: '')]
                    
                    if (params.CHOOSE == 'No') {
                        echo "Did not choose Yes, so what do we do now?"
                    }
                    if (params.CHOOSE == 'Yes'){
                        gv.testImage()
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                script {
                    env.ENV = input message: "Select the environment to deploy to", ok: "Done", parameters: [choice(name: 'ONE', choices: ['dev', 'staging', 'prod'], description: '')]                    
                    echo "Deploying to ${params.ENV}"
                    gv.deployImage()
                }
            }
        }
    }
}