#!/usr/bin/env groovy
def gv

pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    parameters {
        booleanParam(name: 'executeTests', defaultValue: true, description: "should execute tests")
    }
    stages {
        stage('init') {
            steps {
                script {
                    gv = load "./jenkins-params-build/script.groovy"
                }
                
            }
        }
        stage('test') {
            when {
                expression {
                    params.executeTests
                }
            }
            steps {
                script {
                    gv.testImage()
                }
            }
        }
        stage('deploy') {
            steps {
                input(
                    message: 'Select environment to deploy to:',
                    parameters [
                        choice(
                            name: 'env',
                            choices: ['dev', 'test', 'prod'],
                            description: 'Environment to deploy to'
                        )
                    ]
                )
                echo 'deploying to ${params.env}'
            }
        }
    }
}
